# Use an official Python runtime as a parent image
FROM postgres

# Set environment varibles
ENV POSTGRES_DB postgres
ENV POSTGRES_USER postgres
ENV POSTGRES_PASSWORD postgres

RUN chmod 777 -R /var/lib/postgresql/data
